### ISSUE TITLE
Bug: Cannot install Extension Pack for Java even manually

### ISSUE THREAD

**Issue by levihuayuzhang** [microsoft/vscode-java-pack#1071]
**Environment:**
Ubuntu 22.04

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic
Sandboxed: No

Whe trying to install Extension Pack for Java, following Error masage pop up:

Error while installing 'Extension Pack for Java' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.

The log shows:

renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at G.downloadExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170668)
    at async G.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)

And even dowlaod the local extension file cannot be installed.

**Comment by Eskibear** [comment]
It's probably because of your networking issue. 

By installing `Extension Pack for Java` with a local vsix file, it also tries installing [these extensions](https://github.com/microsoft/vscode-java-pack#extensions-included), which might require downloading from marketplace if any of them is absent.

A workaround for you would be, manually downloading all above extensions, and install them first before you finally install Extension Pack for Java.
