### ISSUE TITLE
Failed to download OpenJdk

### ISSUE THREAD

**Issue by KnaupNica** [microsoft/vscode-java-pack#1141]
![image](https://user-images.githubusercontent.com/123362497/214001929-616fcc2f-63c5-4d02-8ed6-e94ce8e6e9be.png)

- VS Code Version: n/a
- Extension Version: n/a
- JDK Type & Version: n/a
- OS Type & Version: Windowds 10 Pro

**Step to Reproduce:**
download coding pack for java
**Expected Behavior:**
install software
**Actual Behavior:**
failed to download OpenJdk
**Related Issues:**

**Comment by Eskibear** [comment]
It's probably due to your networking issue. See https://stackoverflow.com/questions/12180552/openssl-error-self-signed-certificate-in-certificate-chain

Two ways to work it around:

- You can download and install a JDK manually and re-run this installer, it will skip the step if an installed JDK is detected.
- Or you install VS Code and [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) by your own.
