### ISSUE TITLE
Could not find or load main class when creating a new package

### ISSUE THREAD

**Issue by Jarvis-ZHChen** [microsoft/vscode-java-pack#167]
step1: create new project from maven (quick start)
step2: create new package, then create a new java file with main method
step3: run this main method.

it seems VSCode cannot generate .class file and folder in 'target' folder. Or should I generate these my self ? what's more weird is that .class file will be generated automatically when restarting VSCode.
![image](https://user-images.githubusercontent.com/45837977/61602496-64da8a00-ac6c-11e9-979e-080528c0e0fd.png)

**Comment by akaroml** [comment]
@testforstephen seems like a project issue. could you take a look?

At the same time, is it possible that you share your project with us?

**Comment by ZhongxuanWang** [comment]
I hope this might be the right answer for you since mine is different...

First compiler made a mistake that rather than this and made me feel nervous. SO I cleaned all the file in the workspace.. and tragedy happened on me.
Another new problem haunted me...And the way I solve it, is re-added my project into workspace and everything's done after then.

hopefully this helps
