### ISSUE TITLE
VSCode requests that Java Development Kit is required on local machine

### ISSUE THREAD

**Issue by jmsnavarro** [microsoft/vscode-java-pack#177]
VSCode requests that Java Development Kit is required in my local machine.

**Environment:**

- VS Code Version: 1.37.1
- Extension Version: 0.7.1
- JDK Type & Version: openjdk version "11.0.4" 2019-07-16
- OS Type & Version: Windows 10 1903 (local), Ubuntu 18.04 LTS (WSL)

**Step to Reproduce:**
1. I have my java project in WSL.
2. VSCode Installed Java Extension Pack remotely.

![image](https://user-images.githubusercontent.com/17264947/63630977-7cce7080-c653-11e9-9ce6-f36dc6da7df3.png)

**Expected Behavior:**
VSCode will not request that JDK is installed on my local machine. OR, is this the default behavior?

**Actual Behavior:**
But VSCode requests that Java Development Kit is required.

![image](https://user-images.githubusercontent.com/17264947/63630984-92439a80-c653-11e9-9fd5-83beb74d0c87.png)

**Related Issues:** 
None so far.

**Comment by akaroml** [comment]
Thanks for the feedback.

The purpose of Java Extension Pack is to provide code understanding for better code editing experience. With that, you get auto-completion, refactoring, testing, etc. It packs various extensions to provide all the features. Among those extensions, `Java Language Support by Red Hat` contributes most of the features and it requires JDK to run. So that's why you get this hint.

Those features come at a cost of extra CPU/memory consumption just like all other language support in VS Code. While we keep improving the performance and features, we are sorry that your experience hasn't been perfect.

To turn off the hint, you can disable the extension by:
![image](https://user-images.githubusercontent.com/16755094/63996356-0be4f800-cb2e-11e9-88fb-994bda329aa3.png)

Again, I encourage you guys to have JDK installed and try those enhancements before disabling it.

**Comment by bpotvin** [comment]
I see that this was close and that's fine with me. I did some additional investigation and I wanted to follow up just to close the loop on my comment above.

I'm not sure that I communicated my concern correctly. I don't have any confusion over the purpose of the various Java-related extensions or the features they provide. In many circumstances, I have no problems with any of the extensions. However, I have a workflow that involves opening files outside of the context of a workspace. Since 1993, I would use notepad, or MEP for that, but vscode is gradually taking their place and it works great for that.

When I open an assembly language file and vscode tells me there are extensions to help with such files, it gives me that "hint" by pop'ing a small box in the lower-right client area.

When I open a c/c++ file in vscode and the c/c++ extension tells me I should configure an include path, it gives me that "hint" by pop'ing a small box in the lower-right client area.

When I open a java file in vscode and the RedHat extension tells me it can't find the jdk, it gives me that "hint" by pop'ing a small box in the lower-right client area.

I have no objections to that behavior; it's appropriate, useful and mostly unobtrusive.

The problem is, the Java Extension Pack does not give such a "hint". It loads it's "Java Overview" page - even if I have un-checked the "Show overview page" - and then stuffs that page in my face, rather that the .java file I opened.

After looking over the code, it would be fairly simple to either 1) remove that behavior, or 2) gate it with a setting. The third option is to not use the extension pack.

Thanks and have a great week!
