### ISSUE TITLE
Add a decompiler to the pack

### ISSUE THREAD

**Issue by iamatypeofwalrus** [microsoft/vscode-java-pack#18]
Hey!

I'd like to propose adding the [Java Decompiler extension](https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler#overview) to this pack.

I've been using the pack on a few projects at my day job. Due to our custom build system our dependencies are mostly prepackaged in Jars. The `go to definition` command makes a reasonable effort to decompile our dependencies out of the box but it isn't able to bring up the implementation details.

The Java decompiler extension works out of the box with the Red Hat extension and is able to decompile the classes and provide implementation details. 👍

**Comment by andxu** [comment]
We need some investigation about whether it is compatible with java debug/test/maven plugins

**Comment by akaroml** [comment]
@testforstephen could you take a look and evaluate the extension?

**Comment by testforstephen** [comment]
I have a try on the decompiler extension, it provides a good feature to decompile the .class file without source file, but missed some important features.

If you want the extension to be added to the pack, i wish to see these two issues to be addressed. At least, solve the first one first.
- The basic language server features don't work in the auto generated code. For example, "Go to Definition" doesn't work in the decompiled code. 
- The decompiled code can't be used for debugging because of line number not match.

// fyi @dgileadi (the author)

**Comment by akaroml** [comment]
Thanks, @testforstephen for the evaluation.

**Comment by thinkiny** [comment]
any progress ?

**Comment by akaroml** [comment]
> any progress ?

There are unresolved issues, see comments from @testforstephen. We need to get those issue addressed before we recommend that extension to everyone by putting it in the extension pack.

In the short term, please install the decompiler extension yourself and see if it resolves your problem. And we appreciate your feedback on how it works.

**Comment by testforstephen** [comment]
redhat java extension has integrated a built-in fernflower decompiler, no need to include a 3rd party decompiler any more.

**Comment by cklee75** [comment]
> redhat java extension has integrated a built-in fernflower decompiler, no need to include a 3rd party decompiler any more.

However the built-in fernflower decompiler does not maintain the original line numbers, even the class or jar still has the debug information.
