### ISSUE TITLE
Java setup with VS Code Insiders

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-java-pack#238]
## Suggestion

Add VS Code Insider support

## Use Cases

Requires VS Code

## Examples

I only have VS Code insiders on my machine.  The following article only works with VS Code, not insiders.  It would be great if I was given the option to run this with Insiders.

https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/java.md

![image](https://user-images.githubusercontent.com/2163001/66227409-fc5b5080-e691-11e9-8ae9-de6f41797f1d.png)

@gregvanl
@hexiaokai

**Comment by Eskibear** [comment]
Insiders support is in the plan but has not been shipped yet. It was not as a first priority because we assumed that insider users should be competent to install and configure the extensions by themselves.

Current implementation is: 
- If an insider version is installed, it will install and configure Java extensions for the insider version.
- Otherwise, it will install latest VSCode stable version (if not installed), and install and configure for the stable version.

**Comment by Eskibear** [comment]
v0.2.0 has been released, carrying the insiders support. Please [re-download](https://aka.ms/vscode-java-installer-win) and give it a try.

**Comment by akaroml** [comment]
Thanks for the contribution.
