### ISSUE TITLE
Failed to install 'vscjava.vscode-java-pack'

### ISSUE THREAD

**Issue by ozzioma** [Microsoft/vscode-java-pack#24]
Why am I getting this error when I try to install

> Failed to install 'vscjava.vscode-java-pack'.

This is my environment
Windows 10 Home x64
JDK 8
Latest Visual Studio Code

Every other extension installs but only Java extensions repeatedly fail.
What could be wrong?

**Comment by andxu** [comment]
@ozzioma Thanks for trying java extensions, could you retry it again and send us the error logs:
![image](https://user-images.githubusercontent.com/17075863/39390130-f3dbf142-4ac2-11e8-84d6-e9c9e6771375.png)

**Comment by ozzioma** [comment]
Here....

![error2](https://user-images.githubusercontent.com/1046981/39390234-96706440-4a89-11e8-872d-dd43da3a129a.PNG)

![error1](https://user-images.githubusercontent.com/1046981/39390235-9b0e5d86-4a89-11e8-8c4d-9c9236215fd2.PNG)


Any idea what could be the issue?

**Comment by ozzioma** [comment]
Any update yet?

**Comment by andxu** [comment]
@ozzioma it is caused by your network, you might have a try on setting up the right proxy for vscode, see https://code.visualstudio.com/docs/setup/network, or manually download and install the extension as a workaround
see also at https://github.com/Microsoft/vscode/issues/42079 and
https://github.com/Microsoft/vscode/issues/42229

**Comment by akaroml** [comment]
@ozzioma please check the comment above and see if that solves your problem.
