### ISSUE TITLE
vscode-java-installer v0.2.1 error

### ISSUE THREAD

**Issue by husseinrf** [microsoft/vscode-java-pack#268]
installer version: 0.2.1
env:
```
os: win32
arch: x64
PATH: C:\Program Files (x86)\Google\Chrome\Application;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Spartix\AppData\Local\Microsoft\WindowsApps;;C:\Users\Spartix\Desktop\Microsoft VS Code\bin
JAVA_HOME: undefined
JDK_HOME: undefined
```
log:
```
[12:04:36 PM] Download JDK
[12:05:24 PM] Download JDK ... [Completed]
[12:05:24 PM] Install JDK
[12:06:14 PM] Install JDK ... [Completed]
[12:06:14 PM] Configure Java Settings
[12:06:14 PM] Configure Java Settings ... [Completed]
[12:06:14 PM] Install Java Extensions
[12:06:14 PM] Error occurred
[12:06:14 PM] Error: spawn C:\Users\Spartix\Desktop\Microsoft VS Code\bin\code.cmd ENOENT

```

**Comment by Eskibear** [comment]
it's odd. 

Please check:
* If file `C:\Users\Spartix\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd` exists and is executable.  You can double click it, see if vscode is open. 
* If `cmd.exe` is located in `C:\WINDOWS\system32`.

**Comment by pavelnoen94** [comment]
I got this error when running the installer. In my case I've removed code.cmd because it showed up in search results. I preffered seeing Visual Studio Code in the search results instead of just "code" without any logo.
![image](https://user-images.githubusercontent.com/38912521/70327179-83fe4080-1836-11ea-9e94-80451ef746a2.png)

**Comment by Eskibear** [comment]
@pavelnoen94 The installer depends on `code.cmd` to install Java Extension Pack for you. You can install the extension pack manually in VSCode. It should work automatically because the installer has configured the required settings.

Thank you for the information, it helps a lot. We might think of ways to improve the user experience for your case, e.g. guide to install extensions mannually...
