### ISSUE TITLE
Extension claims to support Gradle but how do you build the project

### ISSUE THREAD

**Issue by xendren** [microsoft/vscode-java-pack#347]
I am unable to locate any documentation on how to use the extension pack when I have an existing gradle project.  How am I supposed to build and execute gradle tasks?  I can execute from the terminal directly, but this isn't gradle support from the extension.  

I have tried using the Gradle Tasks extension, but it doesn't appear to share settings with the Java extension, so I cannot get consistent results between a Terminal build and the VS Code UI.  This severely hampers our team moving to VS Code as a primary Java development tool, so I'd love to figure out how to fix or work around these things.  
Any help would be appreciated.

**Comment by akaroml** [comment]
Thank you for your feedback. Java Language Server provides Gradle support by automatically import and builds a project whenever it's opened. With that, you'll be able to do code navigation, editing, refactoring and debugging. Furthermore, you are also able the see all the packages and classes with the help of the Java Dependency Viewer extension.

However, visualizing and executing goals are not part of the support. And the existing Gradle extension does not talk to Java LS and that's the reason for the inconsistency.

Our focus was on Maven and now VS Code is pretty capable of dealing with Maven goals. We'll definitely work on Gradle this year. We'd love to help your team on board. Please let us know about the scenario and problems so we could further engage.

**Comment by badsyntax** [comment]
Hi. As the author of the [gradle tasks](https://github.com/badsyntax/vscode-gradle) extension, I'm also happy to work with the authors of `vscode-java-pack` to provide better support, or to help add gradle tasks features to `vscode-java-pack`.

@xendren can you clarify exactly what you mean when you say:

> I have tried using the Gradle Tasks extension, but it doesn't appear to share settings with the Java extension, 

Can you provide an example of this? Thanks.

**Comment by xendren** [comment]
@badsyntax Thank you for the quick response.  We are trying to retool our Java team toward a more flexible and simplified toolset as we progress our CI/CD efforts.  We are coming from an Ant based build strategy, but we need more flexibility without having to write custom tags.  For all of the benefits that Maven provides, it is still too rigid when it comes to simple things like using a custom artifact repository.  Gradle's approach seems to be exactly what we need, but it seems the majority of the world highly favors Maven.  

We have been very impressed with VS Code as a simplified IDE, but we have found a few flaws in the bundled extension process.  We get inconsistent results seemingly due to each extension having unique settings.  The simple act of trying to specify the location of a JDK seems to not be shared or consistent.  For instance, the Gradle Tasks extension is part of the Microsoft Java bundle, but compiling from a Gradle Task seems to complete successfully even though the UI is showing imports with class not found markers.  We have also seen seemingly random errors appear from Maven stating a jar file isn't present yet the jar file is clearly present in UI and runs without error.

**Comment by xendren** [comment]
> Hi. As the author of the [gradle tasks](https://github.com/badsyntax/vscode-gradle) extension, I'm also happy to work with the authors of `vscode-java-pack` to provide better support, or to help add gradle tasks features to `vscode-java`.
> 
> @xendren can you clarify exactly what you mean when you say:
> 
> > I have tried using the Gradle Tasks extension, but it doesn't appear to share settings with the Java extension,
> 
> Can you provide an example of this? Thanks.
> 
> [EDIT] Ok I guess this refers to all the settings here: https://github.com/redhat-developer/vscode-java/blob/master/README.md#supported-vs-code-settings
> I am considering to read those settings to provide better support between the two extensions. I am tracking this here: [badsyntax/vscode-gradle#249 (comment)](https://github.com/badsyntax/vscode-gradle/issues/249#issuecomment-609026174)

Yes.  The disconnect between some of those settings is one of the headaches.

**Comment by badsyntax** [comment]
Thanks for the detailed response, this is great feedback.

> For instance, the Gradle Tasks extension is part of the Microsoft Java bundle, but compiling from a Gradle Task seems to complete successfully even though the UI is showing imports with class not found markers. 

To clarify, the [Gradle Tasks](https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-gradle) extension is not part of the Java bundle. It is an independent extension, and as @akaroml mentioned, does not use the language server provided by `vscode-java`, hence the inconsistencies.

Saying that, I have pushed a fix for this. Now, when running tasks via the [Gradle Tasks](https://github.com/badsyntax/vscode-gradle) extension, the java project is updated via the [Java language server](https://github.com/redhat-developer/vscode-java) (if installed). If you are compiling files via `Gradle Tasks`, you'll now see the class references updated in the editor.

> The simple act of trying to specify the location of a JDK seems to not be shared or consistent.

I've added support for reading the `java.home` config. Now both [Java language support](https://github.com/redhat-developer/vscode-java) and [Gradle Tasks](https://github.com/badsyntax/vscode-gradle) will use the JDK specified by `java.home`.

If I have time, I will explore the possibility of using the [Java language server](https://github.com/redhat-developer/vscode-java) to discover and run tasks. One reason why I haven't done so already, is for performance reasons. I don't need a "full sync" of the project to list gradle tasks (eg I don't need all packages downloaded), which is why it's very fast to list gradle tasks (via [Gradle Tasks](https://github.com/badsyntax/vscode-gradle)) but slow to build and sync the project (via [Java Language Support](https://github.com/redhat-developer/vscode-java/)). It's important to note, that both the [Gradle Tasks server](https://github.com/badsyntax/vscode-gradle) and the [Java language server](https://github.com/redhat-developer/vscode-java/) use the Gradle Tooling API behind the scenes, so there's no possibility of conflicting processes, as Gradle manages these processes itself via its' daemons. 

When I have some time I will explore using the java language server provided by [`vscode-java`](https://github.com/redhat-developer/vscode-java). I'm not yet fully convinced it's the correct tool to use for discovering and running tasks. Behind the scenes it uses buildship which is exactly the right tool, but i'm not sure sure the Language server protocols allow for discovering & running tasks, as it's outside the scope of the text editor. (But I'm quite familiar with the language server and need to investigate more.)

To take advantage of the updates mentioned above, please update [`Gradle Tasks`](https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-gradle) to at least version 2.5.1.

**Comment by akaroml** [comment]
@badsyntax thank you very much for the effort. We do want to enhance the Gradle experience in the future. Keep in touch!

@xendren I'm closing this issue since @badsyntax already provided a solution.
