### ISSUE TITLE
Bug: Error reporting not synchronized with editor

### ISSUE THREAD

**Issue by GaZaTu** [microsoft/vscode-java-pack#485]
**Environment:**

- VS Code Version: 1.49.2
- Extension Version: 0.10.0
- JDK Type & Version: openjdk1.8 | openjdk11 | openjdk14
- OS Type & Version: Linux openSUSE Leap 42.2

**Step to Reproduce:**

I actually have no idea, it just started to be like this since one of the previous updates.
I don't update too often so i don't know which update in specific.

**Expected Behavior:**

- Error reporting to work in the editor without opening the same file twice in different editors.
- Test runner code lenses to be above the testXD() method

**Actual Behavior:**

- Error squiggles (or w/e they're called) aren't visible when opening a file from the sidebar
- When i open the same file through the "Problems" panel, it opens in a second editor tab which then shows error squiggles
- Test runner code lenses don't work at all anymore

![screencap2](https://user-images.githubusercontent.com/17497826/95466172-5b763400-097c-11eb-8b51-fb7913cdcee5.gif)

**Related Issues:** 

I have no idea. tbh i don't even know if this is the correct project, could very well be an Issue with redhat-java,
but then again, the test runner code lenses are also gone.

If you think this is the wrong project for this issue i'll close it and move it to redhat-java.

**Comment by testforstephen** [comment]
It looks a little weird from the screencast. Both the **PROBLEMS** view and **Breadcrumb** shows an absolute path for the file TextDocumentTest.java. Looks like it doesn't belong to your current workspace.

Because if it's a file inside your workspace, VS Code will show a relative path for it, see the following.

![image](https://user-images.githubusercontent.com/14052197/95548105-f6cbdf80-0a36-11eb-906e-4d77e03e72d3.png)

Could you try **F1 ->  Java: Clean the Java language server workspace**?

**Comment by GaZaTu** [comment]
I did that before and did it again just now but the issue is still there.

I just created an empty Maven project with just a main() method in it and there it worked correctly until i closed VSCode and opened the project again.

**Comment by testforstephen** [comment]
Looks something wrong in your VS Code. Did you observe the exception in other languages such as javascript?

Also, could you update your VS Code (1.50.0) and all Java extensions to the latest version?

**Comment by GaZaTu** [comment]
I couldn't reproduce this issue with any javascript or typescript code.

Updated VSCode to 1.50.0, java extensions were up to date already, disabled all non java extensions, cleaned java ls workspace again.

I'm still having this issue.

**Comment by testforstephen** [comment]
Install another extension version.
![image](https://user-images.githubusercontent.com/14052197/95558291-980f6180-0a48-11eb-8e6b-e2f434915610.png)

**Comment by GaZaTu** [comment]
OK, turns out i'm stupid.
The path I used to open my projects contains a symlink. That's why it didn't work.
If i open the project without using a symlink everything works as expected.
Sorry for the inconvenience and thx for helping.

**Comment by testforstephen** [comment]
Thanks to let me know. I was also suspicious at first that it was because of the symbolic link. But when i try to create a symbolic link in macOS via `ln -s sourceProject linkProject` and open `linkProject` in VS Code, it works well.

Could you mind sharing your symlinks in your project? Want to know whether it's more complex than i used.

**Comment by GaZaTu** [comment]
In my home directory (which is on a different drive, a network drive to be more specific) is a symlink which points to "/opt/home/iuk23113" in my example. When i open a project inside of VSCode or Dolphin (open with VSCode) using a path with this symlink, this issue comes up.
